### ISSUE TITLE
Authentication changed: player not authenticated

### ISSUE THREAD

**Issue by fboulegue** [jackcook/GCHelper#2]
I added the Repo to my project and try to authenticated the user but i always directly fail with

he requested operation could not be completed because this application is not recognized by Game Center.

**Comment by JMStudiosJoe** [comment]
When I try using the authenticating method: GCHelper.sharedInstance.authenticateLocalUser()    
I get:
 Authenticating local user... 
Authentication changed: player not authenticated
Authentication changed: player not authenticated

I am using a button to call the authenticate local player and when I tap the button again all I get is Authenticating local user...

Any ideas?

**Comment by jackcook** [comment]
Make sure that in the Game Center portion of the Settings app, you have "Sandbox" turned on.
![Screenshot]
(http://puu.sh/eokPx/8c053c61e5.png)

**Comment by JMStudiosJoe** [comment]
Thank you for the fast response. I have that on since I am able to access and login with the obj c code from the same tutorial you provided. I am able to work with gamekit in obj c but I would like to use swift instead. Thank you for your time I look forward to hearing from you soon.

- Joey Richardson

**Comment by JMStudiosJoe** [comment]
Do you have a tutorial on how to use your repo for a Game Center project? I have been able to login with:

var localPlayer = GKLocalPlayer.localPlayer()
        localPlayer.authenticateHandler =
            {(viewController : UIViewController!, error : NSError!) -> Void in
            if ((viewController) != nil)
            {
                self.presentViewController(viewController, animated: true, completion: nil)
            }
            else
            {
                
                println((GKLocalPlayer.localPlayer().authenticated))
                                GCHelper.sharedInstance.findMatchWithMinPlayers(2, maxPlayers: 4, viewController: self, delegate: self)
                
                GCHelper.sharedInstance.lookupPlayers()
            }

Everything works up until i add in the lookupPlayers() method then the app crashes, with wrapping a nil object at:

let playerIDs = match.players.map { ($0 as GKPlayer).playerID }
in the lookupPlayers() method. I think I am calling the methods in the wrong order or not using them properly, any tutorial or advice would be greatly appreciated, thank you!

**Comment by JMStudiosJoe** [comment]
I am now able to connect to devices to a game but when I get to the part 2 of the tutorial in the networking section, in the tutorial you followed, I get lost in your code. Is everything we need for GameKit functionality in your helper class? For instance deciding who is player one, how to send to each device the winner and loser.

**Comment by jackcook** [comment]
I haven't personally attempted an app that numbers players, but it should definitely be possible using the `match:didReceiveData:fromPlayer:` delegate method in your code.

**Comment by JMStudiosJoe** [comment]
K I will let you know what I find. Thank you!

**Comment by jackcook** [comment]
This isn't so much an issue with GCHelper as much as a specific situation in your code. Because of this, I'm closing the issue.
