### ISSUE TITLE
a few warnings in Xcode 8.3

### ISSUE THREAD

**Issue by squillopmedia** [jackcook/GCHelper#23]
hi, not a big deal, but just updated to Xcode 8.3 and I am using your (very cool) GC Helper. 
Now seeing a few warnings related to it. 

they are all: 
String interpolation produces a debug description for an optional value; did you mean to make this explicit ?

as i say, not a big deal at all, just thought i'd mention it.

thanks for your awesome code.

**Comment by jackcook** [comment]
Fixed with #24
