### ISSUE TITLE
Notification Name Invalid

### ISSUE THREAD

**Issue by BCtopics** [jackcook/GCHelper#26]
On commit 'e8f816ad06505de81de0af4945c4668281c30c80' changing 'NSNotification.Name(rawValue: GKPlayerAuthenticationDidChangeNotificationName) ' to 'Notification.Name.GKPlayerAuthenticationDidChangeNotificationName' caused builds to fail occasionally.

**Comment by jackcook** [comment]
Yeah I didn't realize that my suggested change didn't compile, this was my bad

**Comment by jackcook** [comment]
Just fixed the build with version 0.4.5
