### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by jackcook** [jackcook/GCHelper#5]
Hey! If you're here to write some unit tests, the only note I have is to use XCTest.

If you're not sure why I wrote this issue, go take a look at the [CocoaPods Testing Jam](http://blog.cocoapods.org/Test-Jammin/).

Thanks!

**Comment by ixgaming** [comment]
Do you plane to add Turn based Games ?

**Comment by jackcook** [comment]
Not myself, but I would consider any pull requests adding the feature.

**Comment by jackcook** [comment]
Seeing that the testing jam is long gone, I'm closing this issue. I might even add some tests myself in the near future.
